name: bitsbull_app
description: App By PRK Technologies

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  carousel_slider: ^2.3.1
  flutter_neumorphic: ^3.0.3
  dio: ^3.0.10
  styled_widget: ^0.2.2
  country_picker: ^1.1.2
  fluttertoast: ^7.1.5
  flutter_masked_text: ^0.8.0
  open_mail_app: ^0.0.3
  pull_to_refresh: ^1.6.3
  modal_bottom_sheet: ^1.0.0+1
  google_fonts: ^1.1.1
  shared_preferences: ^0.5.12+4
  loading_gifs: ^0.2.3
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^5.7.10
  image_picker: ^0.6.7+17
  local_auth: ^0.6.3+4
  palette_generator: ^0.2.3
  vector_math: ^2.0.8
  rflutter_alert:
    git: git://github.com/RatelHub/rflutter_alert.git
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/market/
    - assets/ilustration/boarding1.png
    - assets/ilustration/noData.png
    - assets/ilustration/boarding2.png
    - assets/ilustration/boarding3.png
    - assets/image/banner/banner1.png
    - assets/image/banner/banner2.png
    - assets/image/banner/banner3.jpg
    - assets/image/banner/banner4.png
    - assets/image/splash_screen.png
    - assets/image/loginHeader.png
    - assets/image/logo.png
    - assets/image/signupHeader.png
    - assets/image/gainers.png
    - assets/image/losers.png
    - assets/image/market/ae.png
    - assets/image/market/aion.png
    - assets/image/market/bat.png
    - assets/image/market/BCH.png
    - assets/image/market/bee.png
    - assets/image/market/bnt.png
    - assets/image/market/btc.png
    - assets/image/market/dnt.png
    - assets/image/market/elf.png
    - assets/image/market/EOS.png
    - assets/image/market/ETC.png
    - assets/image/market/eth.png
    - assets/image/market/NEO.png
    - assets/image/market/RIPLE.png
    - assets/image/market/bitcoin.png
    - assets/image/article1.jpg
    - assets/image/create_wallet.png
    - assets/image/News_Image/Asia.jpg
    - assets/image/News_Image/BlockStream.jpg
    - assets/image/News_Image/BNB.jpg
    - assets/image/News_Image/CBOE.jpg
    - assets/image/News_Image/CryptoBroker.jpg
    - assets/image/News_Image/EOSget.jpg
    - assets/image/News_Image/MarketSentiment.jpg
    - assets/image/News_Image/Mt.Gox.jpg
    - assets/image/News_Image/NewCripto.jpg
    - assets/image/News_Image/Twitter.jpg
    - assets/image/News_Image/YouCan.jpg
    - assets/image/News_Image/Ziliqa.jpg
    - assets/image/setting/lightMode.png
    - assets/image/setting/nightMode.png
    - assets/image/qrCode.png
    - assets/image/messageAppbar.png
    - assets/image/T1_noMessage.png
    - assets/image/icon/icon_file.png
    - assets/image/icon/icon_image.png
    - assets/image/icon/icon_microphone.png
    - assets/image/icon/icon_monitor.png
    - assets/image/icon/icon_video.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/avatars/avatar-7.png
    - assets/avatars/avatar-7-line.png
    - assets/avatars/default-avatar.jpg
    - assets/image/crypto_icon/icon_bitcoin.png
    - assets/image/crypto_icon/icon_bee.png
    - assets/image/crypto_icon/icon_elf.png
    - assets/image/crypto_icon/icon_eth.png
    - assets/image/crypto_icon/icon_lnc.png
    - assets/image/Template_2_image/tabBar.png
    - assets/image/Template_3/people.png
    - assets/image/Template_3/scan.png
    - assets/image/Template_3/transfer.png
    - assets/image/Template_3/menu_bus.png
    - assets/image/Template_3/menu_home.png
    - assets/image/Template_3/menu_shopping.png
    - assets/image/Template_3/menu_tv.png
    - assets/image/Template_3/slackLogo.png
    - assets/image/Template_3/solariaLogo.jpg
    - assets/image/Template_3/twitchLogo.png
    - assets/image/Template_3/finance_layout/bils_finance.png
    - assets/image/Template_3/finance_layout/doctor_finance.png
    - assets/image/Template_3/finance_layout/hangout_finance.png
    - assets/image/Template_3/finance_layout/lifeStyle_finance.png
    - assets/image/Template_3/finance_layout/workout_finance.png
    - assets/image/Template_3/deals_layout/buildingMenu.png
    - assets/image/Template_3/deals_layout/cardMenu.png
    - assets/image/Template_3/deals_layout/financeMenu.png
    - assets/image/Template_3/deals_layout/findMenu.png
    - assets/image/Template_3/deals_layout/giveMenu.png
    - assets/image/Template_3/deals_layout/growthMenu.png
    - assets/image/Template_3/deals_layout/locationMenu.png
    - assets/image/Template_3/deals_layout/moneyMenu.png
    - assets/image/Template_3/deals_layout/saveMenu.png
    - assets/image/Template_3/deals_layout/shareMenu.png
    - assets/image/Template_3/historyEmpty.png
    - assets/icon/Template4/aboutapp.png
    - assets/icon/Template4/callcenter.png
    - assets/icon/Template4/chat.png
    - assets/icon/Template4/creditAcount.png
    - assets/icon/Template4/notification.png
    - assets/icon/Template4/setting.png
    - assets/icon/Template4/truck.png
    - assets/image/Template_4/notifications.png
    - assets/image/Template_4/creditCardVisa.png
    - assets/image/Template_4/credit.png
    - assets/image/Template_4/contact_us.png
    - assets/image/Template_4/noMessage.png
    - assets/image/Template_5/noTransaction.png
    - assets/image/Template_5/alarm.png
    - assets/image/Template_5/creditCard.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
